#monitors a webserver and emails if it fails, also pings and logs to syslog
#this was a monitoring is down and I want to know when this crap changes
#and I need to know in 10 minutes kind of script...don't judge me :)



#!/bin/bash
#
#################################################
#
HOST=<server ip>
SYSLOG0="server is not reachable"
SYSLOG1="currently reachable:"
HOSTDOWN=$"server IS DOWN"
EXHASH='47f1a288c7fc16379ba3f41a9' #set to expected hash
#
#################################################
#
#Try connection to Webserver and dump results
/usr/bin/nc -v $HOST 80 < /root/server001_connection/get.sh > get.results
#
#Parse down and hash output
CON=$(tail -n 1 get.results | md5sum | cut -c 1-25)
#
#Compare expected ouput with actual
if [ "$CON" == "$EXHASH" ]; then

       #server001 is responding fine
       cat /dev/null > /root/server001_connection/get.results

       #echo "Syslog message server001 is fine"
       logger $SYSLOG1 TCP Connect
else

       #echo "Syslog message server001 is hosed"
       logger $SYSLOG0 TCP Connect

       #Send email because server001 is hosed
       /usr/sbin/sendmail -t < /root/server001_connection/server001down.txt

       #Clear temp results file
       cat /dev/null > /root/server001_connection/get.results

       #Try to ping host to verify down host status
       ping -c 3 -w 5 $HOST &>/dev/null
               if [ $? -ne 0 ] ; then
                       #Log ping not unsuccessful
                       logger $SYSLOG0 ping
               else
                       #Log ping successful
                       logger $SYSLOG1 ping
               fi
fi



#####
#THIS IS THE EMAIL TEMPLATE
#####
server001down.txt
To:email@email.com
Subject: server001 is Down!
From: monscript

This message generated by: /root/server001_connection/tcpconn_icmp_mon.sh

This script tries to verify connectivity to the server001 service running on port 80.
If this fails it will send an email to noc@

The script will also attempt to ping the host and will log the results in /var/log/messages.
Ping failures are not emailed.

This process happens every 15 minutes.

get.sh
GET /
