#!/bin/bash
#
#2009 Chase Pettet
#This script should be called by the drbd.conf file using the out-of-sync handler
#out-of-sync "/usr/lib/drbd/notify-out-of-sync.sh $RESOURCE $EMAIL";
#
#
EMAIL="$2"
MESSAGE="./drbd-out-of-sync.message"
hbstatus=$(cl_status rscstatus)
drbdstatus=$(grep st: /proc/drbd | cut -d: -f4 | cut -c 1-3)
date=$(date)
#
touch ./drbd-out-of-sync.message

log.event ()
{
               logger "DRBD Out Of Sync Detected!"
               logger "Out of sync resource: $1".
}

send.email ()
{
       #Building an email message
       echo "This message was generated by $HOSTNAME." >> $MESSAGE
       echo "Script: $0" >> $MESSAGE
       echo -e "This script runs when DRBD detects an out of sync resource. \n
       This should be investigated ASAP. \n" >> $MESSAGE
       echo "Currently DRBD status is: $drbdstatus." >> $MESSAGE
       echo "Heartbeat status is: $hbstatus." >> $MESSAGE
       echo "This occured on: $date."  >> $MESSAGE

       #
       #Defining The subject and mailing the message
       SUBJECT="Alert: DRBD Resource $1 on $HOSTNAME out of sync!"
       mail -s "$SUBJECT" "$EMAIL" < $MESSAGE
}

