#!/bin/bash
#
#
#2009 Chase Pettet
#This script should be called by the drbd.conf file using the drb-split-brain handler
#split-brain ""/usr/lib/drbd/notify-split-brain.sh $RESOURCE $EMAIL";
#
EMAIL="$2"
MESSAGE="./drbd-split-brain.message"
hbstatus=$(cl_status rscstatus)
drbdstatus=$(grep st: /proc/drbd | cut -d: -f4 | cut -c 1-3)
date=$(date)
#
touch ./drbd-split-brain.message

log.event ()
{
               logger "DRBD Split Brain Situation Detected!"
               logger "DRBD Split Brain resource: $1".
}

send.email ()
{
       #Building an email message
       echo "This message was generated by $HOSTNAME." >> $MESSAGE
       echo "Script: $0" >> $MESSAGE
       echo -e "This script runs when DRBD detects a split brain situation. \n
       This should be investigated ASAP. \n" >> $MESSAGE
       echo "Currently DRBD status is: $drbdstatus." >> $MESSAGE
       echo "Heartbeat status is: $hbstatus." >> $MESSAGE
       echo "This occured on: $date."  >> $MESSAGE
       #
       #Defining The subject and mailing the message
       SUBJECT="Alert: DRBD Resource $1 on $HOSTNAME detects Split Brain!"
       mail -s "$SUBJECT" "$EMAIL" < $MESSAGE
}

log.event $1
send.email $1
rm -f ./drbd-split-brain.message

exit 0
